### ISSUE TITLE
Broken on kernel 6.0.2 (openSUSE TW)

### ISSUE THREAD

**Issue by porcupinecoder** [FaridZelli/ISW-Modern#14]
`syste
mctl status isw@SILENT.service` returns

`Oct 22 12:20:07 localhost.localdomain isw[1131]:   File "/usr/lib64/python3.10/argparse.py", line 2451, in _get_values
Oct 22 12:20:07 localhost.localdomain isw[1131]:     value = self._get_value(action, arg_string)
Oct 22 12:20:07 localhost.localdomain isw[1131]:   File "/usr/lib64/python3.10/argparse.py", line 2484, in _get_value
Oct 22 12:20:07 localhost.localdomain isw[1131]:     result = type_func(arg_string)
Oct 22 12:20:07 localhost.localdomain isw[1131]:   File "/usr/bin/isw", line 336, in ec_write
Oct 22 12:20:07 localhost.localdomain isw[1131]:     with open(EC_IO_FILE,'r+b') as file:
Oct 22 12:20:07 localhost.localdomain isw[1131]: FileNotFoundError: [Errno 2] No such file or directory: '/dev/ec'`

after distroupdate that included the latest kernel (6.0.2)

edit: nevermind, reinstall acpi_ec did the trick :)

**Comment by FaridZelli** [comment]
Good to know, actually I'm switching from EndeavourOS to openSUSE Tumbleweed.
Will add new instructions 👍

**Comment by agramian** [comment]
I'm experiencing this issue as well. If I manually create a blank `/dev/ec` file and restart the service, then it works but `/dev/ec` does not persist across reboots so I need to repeat that process every time.

I've looked at the related discussion #3 and #5 but the suggested solutions don't solve this.

Do you have any suggestions for fan control on an MSI laptop? Are you still using one of these projects yourself?
I also tried using the registers from this project to create an nbfc config to write the values for the advanced fan mode and 6 levels on initialization but I wasn't able to get it to work.

**Comment by porcupinecoder** [comment]
> I'm experiencing this issue as well. If I manually create a blank `/dev/ec` file and restart the service, then it works but `/dev/ec` does not persist across reboots so I need to repeat that process every time.
> 
> I've looked at the related discussion #3 and #5 but the suggested solutions don't solve this.
> 
> Do you have any suggestions for fan control on an MSI laptop? Are you still using one of these projects yourself? I also tried using the registers from this project to create an nbfc config to write the values for the advanced fan mode and 6 levels on initialization but I wasn't able to get it to work.


even though no longer under development, isw-modern seems to function fine for me as long as i keep the acpi_ec kernel module installed (https://github.com/musikid/acpi_ec)

need to run sudo ./uninstall && sudo /install and reboot every kernel update, but thats only every few weeks so its an acceptable chore for me :)

there may be other, better projects since i started using this, but i have not been keeping track as ive been satisfied with isw-modern

**Comment by FaridZelli** [comment]
> Do you have any suggestions for fan control on an MSI laptop?

[MControlCenter](https://github.com/dmitry-s93/MControlCenter) is the only project still in development that I'm aware of, the interface looks nice from the screenshots.   
Glad you guys still use ISW! I miss my MSI laptop 🥲
