### ISSUE TITLE
ec_sys deprecated - solutions?

### ISSUE THREAD

**Issue by Shadowphoenix** [FaridZelli/ISW-Modern#3]
as off recently, MLFC also has the problem with ec_sys missing - are you aware of a workaround or how to reinstall the module? renders both yoypa's isw and MLFC currently unusable to me it seems (Arch with latest kernel available in core-repo).

**Comment by Shadowphoenix** [comment]
update: browsed your stuff a bit - is https://github.com/FaridZelli/acpi_ec the thing we need to get it working? if yes i would be able to mention that in the corresponding MLFC-Issue.

**Comment by FaridZelli** [comment]
That isn't my project, it's a fork of https://github.com/musikid/acpi_ec as you can see under [Resources](https://github.com/FaridZelli/ISW-Modern#useful-resources).   
   
It's essentially just a DKMS clone of ec_sys, so (at least in theory) this should work for any fan control utility which used to rely on direct EC access. Maxim is aware of the issue, hopefully MLFC will switch to [BeardOverflow's msi-ec Module](https://github.com/BeardOverflow/msi-ec) as it's a much better (and safer) long term solution.   
   
If you want to use a tool with acpi_ec, you need to change the EC address from '/sys/kernel/debug/ec/ec0/io' to '/dev/ec' within the program, as stated in the [readme file](https://github.com/musikid/acpi_ec#acpi_ec). As for MSI laptops, you can use my fork of ISW to silence the fans for now. Please do let me know if you encounter any issues with the instructions, I'm currently using ISW Modern on my MSI Modern 15 (10th Gen) running EndeavourOS, so technically it should be the same on vanilla Arch.

**Comment by Shadowphoenix** [comment]
thx bud for the clarification - well fannoise is not a problem for me, but i might be able to use this as a way to get MLFC back up and running ^^

**Comment by kphanipavan** [comment]
Hello!!

I have created an application called [PredatorNonSense](https://github.com/kphanipavan/PredatorNonSense) which modifies the EC to perform certain tasks on Acer's Predator Helios 300 laptop.

I was migrating to Fedora 36 from Kubuntu 20.04 and was faced with the same issue,`/sys/kernel/debug/ec/ec0/io not found`. Thanks to your [acpi_ec](https://github.com/FaridZelli/acpi_ec) and the [original repo](https://github.com/musikid/acpi_ec)I was able to get it working on newer kernels.

**Comment by FaridZelli** [comment]
Glad it solved the problem! Again, you should be thanking @musikid, not me 🙂
