### ISSUE TITLE
MSI Delta 15

### ISSUE THREAD

**Issue by mccakx** [FaridZelli/ISW-Modern#6]
Hi !
I hope this information will be helpful to expanding MSI Laptop support 

```
isw -cp MSI_ADDRESS_DEFAULT

EC dump 
       00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
000000 00 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000020 00 00 00 00 00 00 00 00 00 00 00 88 e0 06 5b 0b  >..............[.<
000030 03 09 01 0d 51 0a 05 00 a0 14 60 3b 10 02 e0 00  >....Q.....`;....<
000040 00 00 63 00 15 12 00 00 de 11 34 41 04 0c 00 00  >..c.......4A....<
000050 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000060 00 00 00 00 00 00 00 00 36 00 37 3c 46 4e 55 5a  >........6.7<FNUZ<
000070 78 2d 00 2d 3c 46 4b 50 50 00 07 03 03 03 03 03  >x-.-<FKPP.......<
000080 39 00 37 3c 46 50 52 57 00 37 00 37 41 46 4b 50  >9.7<FPRW.7.7AFKP<
000090 50 00 07 03 03 03 03 03 00 00 73 00 00 66 00 00  >P.........s..f..<
0000a0 31 35 43 4b 45 4d 53 31 2e 31 30 38 30 39 30 32  >15CKEMS1.1080902<
0000b0 32 30 32 31 31 37 3a 30 39 3a 33 34 15 12 00 68  >202117:09:34...h<
0000c0 00 07 25 2e 30 9e c0 00 00 65 00 91 00 c9 14 00  >..%.0....e......<
0000d0 00 00 00 00 7f a1 00 00 30 d0 36 80 00 16 07 19  >........0.6.....<
0000e0 e2 02 00 01 10 00 00 00 00 00 34 f0 00 a1 00 e4  >..........4.....<
0000f0 00 00 c1 83 0c 00 05 00 00 00 00 00 00 00 00 00  >................<
000100

Profile dump 
Value       set @ address        Fan mode
0xc(12)     0xf4(byte244)        Auto

Value       set @ address        Charging below - stop @
0xe4(228)   0xef(byte239)        90% - 100%

-----------CPU-----------        -----------GPU-----------
Value       set @ address        Value       set @ address
0x37(55°C)  0x6a(byte106)        0x37(55°C)  0x82(byte130)
0x3c(60°C)  0x6b(byte107)        0x3c(60°C)  0x83(byte131)
0x46(70°C)  0x6c(byte108)        0x46(70°C)  0x84(byte132)
0x4e(78°C)  0x6d(byte109)        0x50(80°C)  0x85(byte133)
0x55(85°C)  0x6e(byte110)        0x52(82°C)  0x86(byte134)
0x5a(90°C)  0x6f(byte111)        0x57(87°C)  0x87(byte135)

0x0(0%)     0x72(byte114)        0x0(0%)     0x8a(byte138)
0x2d(45%)   0x73(byte115)        0x37(55%)   0x8b(byte139)
0x3c(60%)   0x74(byte116)        0x41(65%)   0x8c(byte140)
0x46(70%)   0x75(byte117)        0x46(70%)   0x8d(byte141)
0x4b(75%)   0x76(byte118)        0x4b(75%)   0x8e(byte142)
0x50(80%)   0x77(byte119)        0x50(80%)   0x8f(byte143)
0x50(80%)   0x78(byte120)        0x50(80%)   0x90(byte144)
```

I only test Coolerboost command  `isw -b on` and it work fine.. didnt test Fan Curve yet..

However why it require to disable secure boot? My laptop with secure boot seems working fine.. yeah i am installing this with secure boot and i use arch.. 
```
bootctl status

System:
 Firmware: UEFI 2.70 (American Megatrends 5.19)
 Secure Boot: enabled (deployed)
 TPM2 Support: yes
 Boot into FW: supported
```

**Comment by FaridZelli** [comment]
Thanks! When coolerboost is working, fan curves are likely fine as well.
   
> However why it require to disable secure boot? My laptop with secure boot seems working fine.. yeah i am installing this with secure boot and i use arch.   
   
Interesting, didn't work with Fedora 36 nor Debian Sid when I was testing. Guess it works fine on Arch, I'd assume you're using shim as most MSI laptops don't have support for custom keys in the UEFI. Also, what bootloader are you currently using?

**Comment by mccakx** [comment]
> Interesting, didn't work with Fedora 36 nor Debian Sid when I was testing. Guess it works fine on Arch, I'd assume you're using shim as most MSI laptops don't have support for custom keys in the UEFI. Also, what bootloader are you currently using?

No.. I am not using SHIM or Preloader.. What i do is Combining the initramfs, kernel parameters, and kernel into a .efi image and i enroll that .efi to the Secure boot list (here is the guide https://wiki.archlinux.org/title/Unified_kernel_image)  .. MSI Laptop support Advance BIOS which allowed you to enroll ur own keys or .efi to the secure boot list and modify it... In my case i just need to press R Shift + R Ctrl + L Alt + F2 in the BIOS to access advance BIOS menu..  Your laptop maybe the same because MSI Laptops kinda popular with its advance BIOS which none other manufacture have..

 I use systemd-boot tho..

**Comment by FaridZelli** [comment]
> What i do is Combining the initramfs, kernel parameters, and kernel into a .efi image
   
Awesome, have you automated that to regenerate after every update?   
   

> MSI Laptop support Advance BIOS   
   
That's amazing, didn't know about the extended UEFI configuration. I was shocked to see manual adjustments for the CPU TDP, no option to disable the dGPU though (but I'd bet that's available on laptops with a MUX switch). It's fascinating how they've made these tweaks user-configurable, and yet we still need to rely on 3rd party utilities to change the fan curve :-]   
   
P.S. I'm on EndeavourOS, using systemd-boot too. GRUB's decryption times were insane.

**Comment by mccakx** [comment]
> Awesome, have you automated that to regenerate after every update?

The .efi file is automatically regenerated when some modules or kernel got updated once u done the config (the one from archwiki).... however i need to sign in again every .efi got regenerated.. so.. there is some downside there.. ig its the safer method than using shim or preloader..

> That's amazing, didn't know about the extended UEFI configuration. I was shocked to see manual adjustments for the CPU TDP, no option to disable the dGPU though (but I'd bet that's available on laptops with a MUX switch). It's fascinating how they've made these tweaks user-configurable, and yet we still need to rely on 3rd party utilities to change the fan curve :-]

My laptop have an option to change the fan curve on the bios.. however it doesnt work.. so i need to rely on utlities  :D
